CREATE OR REPLACE VIEW FINAL_DATA_ML AS
SELECT
    ID,
    AGE,
    GENDER,
    BMI,
    WORKOUT_TYPE,
    SESSION_DURATION__HOURS_,
    AVG_BPM,
    PCT_HRR,
    CALORIES_BURNED,
    EXPERIENCE_LEVEL
FROM FINAL_DATA
WHERE CALORIES_BURNED IS NOT NULL;
